version: '3'

services:
  mariadb-cce:
    build: ./alpine-mariadb
    environment:
      MYSQL_DATABASE: 'wordpress'
      MYSQL_PASSWORD: 'supersecret'
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_USER: 'wpuser'
    volumes:
      - ./mysql-data:/var/lib/mysql

  wordpress-cce:
    image: 'yobasystems/alpine-php-wordpress'
    depends_on:
      - mariadb-cce
    ports:
      - '9180:80'
    links:
      - mariadb-cce:mariadb
      - mailcatcher-cce:mailcatcher
    environment:
      VIRTUAL_HOST: 'utsa-cce.dev'
      WP_ENV: 'LOCAL'
    volumes:
      - ./utsa-default-wordpress:/usr/html

  phpmyadmin-cce:
    image: 'phpmyadmin/phpmyadmin'
    depends_on:
      - mariadb-cce
    ports:
      - '9188:80'
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
    links:
      - mariadb-cce:db

  mailcatcher-cce:
    image: tophfr/mailcatcher
    ports:
      - 9125:80
