version: '2'

services:
  mariadb:
    image: 'yobasystems/alpine-mariadb'
    environment:
      MYSQL_DATABASE: 'wordpress'
      MYSQL_PASSWORD: 'supersecret'
      MYSQL_ROOT_PASSWORD: 'foo'
      MYSQL_USER: 'wpuser'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql

  wordpress:
    image: 'yobasystems/alpine-php-wordpress'
    environment:
      WP_ENV: 'LOCAL'
    depends_on:
      - mariadb
    ports:
      - '8000:80'
    links:
      - mariadb:mariadb
    environment:
      - VIRTUAL_HOST=utsa-default.dev
    volumes:
      - ./web-data:/usr/html
