version: '2'

services:
  mariadb:
    build: ./alpine-mariadb
    environment:
      MYSQL_DATABASE: 'wordpress'
      MYSQL_PASSWORD: 'supersecret'
      MYSQL_ROOT_PASSWORD: 'supersecret'
      MYSQL_USER: 'wpuser'
    #ports:
    #    - '3306:3306'
    #expose:
    #      - '3306'
    volumes:
      - ./mysql-data:/var/lib/mysql

  wordpress:
    build: ./wordpress
    depends_on:
      - mariadb
    expose:
      - "80"
    ports:
      - "8282:80"
    links:
      - mariadb:mariadb
    environment:
      VIRTUAL_HOST: 'utsa-default.dev'
      WP_ENV: 'LOCAL'
    volumes:
      - ./utsa-default-wordpress:/usr/html

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    depends_on:
      - mariadb
    ports:
      - '8181:80'
    environment:
      MYSQL_ROOT_PASSWORD: 'supersecret'
    links:
      - mariadb:db
